[project]
name = "coffee-intake-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "hyperopt>=0.2.7",
    "imblearn>=0.0",
    "import-ipynb>=0.2",
    "mlflow[databricks]>=3.5.1",
    "optuna>=4.6.0",
    "optuna-integration[mlflow]>=4.6.0",
    "pandas>=2.3.2",
    "polars>=1.33.1",
    "scikit-learn>=1.7.2",
    "seaborn>=0.13.2",
]
