[project]
name = "coffee-intake-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.30.1",
    "pandas>=2.3.2",
    "polars>=1.33.1",
    "seaborn>=0.13.2",
]
